config/routes.rb
Rails.application.routes.draw do
  get 'hello/index'
  root 'hello#index'

  # Begin Header Routes
    get 'hello/about'
    get 'hello/blogs'
    get 'hello/login'
    get 'hello/products'
  # End Header Routes

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/views/hello/about.html.erb
<%= render 'layouts/navbar' %>
<%= stylesheet_link_tag "universal.min" %>

<container>
  <h1> About Us </h1>
  <div><%= link_to 'Home', hello_index_path %></div>
</container>

app/views/hello/blogs.html.erb
<%= render 'layouts/navbar' %>
<%= stylesheet_link_tag "universal.min" %>

<container>
  <h1>Blogs</h1>
  <div><%= link_to 'Home', hello_index_path %></div>
</container>

app/views/hello/index.html.erb
<%= stylesheet_link_tag "home.min" %>
<%= stylesheet_link_tag "universal.min" %>

<%= render 'layouts/navbar' %>

<container>
  <h1 class="home-page-header">Hello There</h1>
  <p>This is the beginning of the new website template.</p>
  <button>Create New User</button>
</container>

app/views/hello/login.html.erb
<%= render 'layouts/navbar' %>
<%= stylesheet_link_tag "universal.min" %>

<container>
  <h1>Login</h1>
  <div><%= link_to 'Home', hello_index_path %></div>
</container>

app/views/hello/products.html.erb
<%= render 'layouts/navbar' %>
<%= stylesheet_link_tag "universal.min" %>

<container>
  <h1>Products</h1>
  <div><%= link_to 'Home', hello_index_path %></div>
</container>

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag "navbar.min.css" %>

<!-- <header> -->
  <!-- <div class="container"> -->
    <nav class="navbar">
      <a class="navbar-logo"><%= image_tag "flame-logo.png", class: "humidifire_logo" %></a>
      <form class="menu-items">
        <div class="btn btn-outline-success"><%= link_to 'Products', hello_products_path %></div>
        <div class="btn btn-outline-success"><%= link_to 'Blogs', hello_blogs_path %></div>
        <div class="btn btn-outline-success"><%= link_to 'About Us', hello_about_path %></div>
        <div class="btn btn-outline-success"><%= link_to 'Login', hello_login_path %></div>
      </form>
    </nav>
  <!-- </div> -->
<!-- </header> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>